# Generated by Django 4.2.3 on 2023-07-17 17:39

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_bodega_direccion_alter_bodega_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='jefe_bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.perfilusuario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='bodega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.bodega'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.perfilusuario'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Usuario'),
        ),
    ]
